spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bugboard26}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:bugboard26supersecretkey1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}

server.port=8081

spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:100MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:100MB}
